force-app/main/default/objects/Que_AsyncRequest__c/Que_AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Que_AsyncRequest</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Que_AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_Params__c.field-meta.xml
<CustomField>
    <fullName>Que_Params__c</fullName>
    <description>Parameters for the current async operation</description>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/dar/DAR_CleanAddresseExecutor.cls
public with sharing class DAR_CleanAddresseExecutor implements Que_IExecutable {
    private static DAR_Client DAR_REST_CLIENT = DAR_Client.getInstance();

    public void execute(Que_AsyncRequest__c asyncRequest){
        Logger.info(new LogMessage('execute({0})', asyncRequest), asyncRequest.Id);

        HttpResponse httpResp = DAR_REST_CLIENT.addresseVask(asyncRequest.Que_Params__c);
    }

    public Boolean retryOnException(Que_AsyncRequest__c asyncRequest, Exception ex){
        String exceptionAsJSON = ExceptionUtil.generateJSONFromException(ex);
        Logger.info(new LogMessage('retryOnException({0})', asyncRequest, exceptionAsJSON), asyncRequest.Id);
        return true;
    }
}