force-app/main/default/objects/Que_AsyncRequest__c/Que_AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Que_AsyncRequest</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Que_AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_Status__c.field-meta.xml
<CustomField>
    <fullName>Que_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Parked</fullName>
            </value>
            <value>
                <fullName>Reconstructed</fullName>
            </value>
            <value>
                <fullName>WaitForResume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/que/Que_AsyncRequestTriggerHandler.cls
public with sharing class Que_AsyncRequestTriggerHandler extends TriggerHandler {
    private static final Que_Service SERVICE_QUE = Que_Service.getInstance();
    private static DML_IOperations DML = DML_Executor.getInstance();


    private List<Que_AsyncRequest__c> triggerNew;
    private List<Que_AsyncRequest__c> triggerOld;
    private Map<Id, Que_AsyncRequest__c> triggerMapNew;
    private Map<Id, Que_AsyncRequest__c> triggerMapOld;

    public Que_AsyncRequestTriggerHandler(){
        this.triggerOld = (List<Que_AsyncRequest__c>) Trigger.old;
        this.triggerNew = (List<Que_AsyncRequest__c>) Trigger.new;
        this.triggerMapNew = (Map<Id, Que_AsyncRequest__c>) Trigger.newMap;
        this.triggerMapOld = (Map<Id, Que_AsyncRequest__c>) Trigger.oldMap;
    }

    public override void afterUpdate() {
        Logger.info('afterUpdate()');
        List<Que_AsyncRequest__c> reconstructedRequests = new List<Que_AsyncRequest__c>();


        for(Id asyncRequestId : triggerMapNew.keySet()){
            Que_AsyncRequest__c oldObject = triggerMapOld.get(asyncRequestId);
            Que_AsyncRequest__c newObject = triggerMapNew.get(asyncRequestId);

            if(newObject.Que_Status__c == 'Reconstructed' && oldObject.Que_Status__c != newObject.Que_Status__c){
                Que_AsyncRequest__c reconstructedAsyncRequest = newObject.clone(false, false, false, false);
                reconstructedAsyncRequest.Que_Status__c = 'In Progress';

                reconstructedRequests.add(reconstructedAsyncRequest);
            }
        }

        if(!reconstructedRequests.isEmpty()){
            DML.doInsert(reconstructedRequests);
        }
    }

    public override void afterInsert() {
        Logger.info('afterInsert()');
        if (Limits.getLimitQueueableJobs() - Limits.getQueueableJobs() > 0){
            try {
                SERVICE_QUE.startQueueable(null);
            } catch (Exception ex) {
                // Ignore for now
            }
        }
    }
}