force-app/main/default/objects/Que_AsyncRequest__c/Que_AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Que_AsyncRequest</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Que_AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_ErrorCount__c.field-meta.xml
<CustomField>
    <fullName>Que_ErrorCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>ErrorCount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_ExecutionEndDate__c.field-meta.xml
<CustomField>
    <fullName>Que_ExecutionEndDate__c</fullName>
    <label>ExecutionEndDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_ExecutionStartDate__c.field-meta.xml
<CustomField>
    <fullName>Que_ExecutionStartDate__c</fullName>
    <label>ExecutionStartDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_Executor__c.field-meta.xml
<CustomField>
    <fullName>Que_Executor__c</fullName>
    <label>Que_Executor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Que_ExecutorExample</fullName>
            </value>
            <value>
                <fullName>DAR_CleanAddresseExecutor</fullName>
            </value>
            <value>
                <fullName>Que_ExampleExecutor</fullName>
                <isActive>false</isActive>
                <label>Que_ExampleExecutor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_Params__c.field-meta.xml
<CustomField>
    <fullName>Que_Params__c</fullName>
    <description>Parameters for the current async operation</description>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_Status__c.field-meta.xml
<CustomField>
    <fullName>Que_Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
                <default>true</default>
                <label>In progress</label>
            </value>
            <value>
                <fullName>Parked</fullName>
            </value>
            <value>
                <fullName>Reconstructed</fullName>
            </value>
            <value>
                <fullName>WaitForResume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/que/Que_SOQL.cls
public with sharing class Que_SOQL {
    //private static instance of the class
    private static Que_SOQL instance = null;

    //private constructor to avoid creating an instance
    //TestVisible to be able to mock
    public Que_SOQL() {
    }

    public static Que_SOQL getInstance() {
        if (instance == null) {
            instance = new Que_SOQL();
        }

        return instance;
    }

    public List<AsyncApexJob> getRunningQueueableJobs() {
        Logger.info(new LogMessage('getRunningJobs() - userinfo.getUserID: {0}', userinfo.getUserID()));

        return [
            SELECT Id, Status, ExtendedStatus
            FROM AsyncApexJob
            WHERE
                JobType = 'Queueable'
                AND (status = 'Queued'
                OR Status = 'Holding')
                AND CreatedById = :userinfo.getUserID()
                AND ApexClass.Name = 'Que_Queueable'
            WITH SECURITY_ENFORCED
        ];
    }

    public List<Que_AsyncRequest__c> getPendingAsyncRequests() {
        Logger.info('getPendingAsyncRequests()');

        return [
            SELECT
                Id,
                Que_Executor__c,
                Que_Params__c,
                Que_ErrorCount__c,
                Que_Status__c,
                Que_ExecutionEndDate__c,
                Que_ExecutionStartDate__c
            FROM Que_AsyncRequest__c
            WHERE Que_Status__c = 'In progress' AND CreatedById = :UserInfo.getUserId()
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
    }

    public List<Que_AsyncRequest__c> getAsyncRequestsForUpdate() {
        Logger.info('getAsyncRequestsForUpdate()');

        return [
            SELECT
                Id,
                Que_Executor__c,
                Que_Params__c,
                Que_ErrorCount__c,
                Que_Status__c,
                Que_ExecutionEndDate__c,
                Que_ExecutionStartDate__c
            FROM Que_AsyncRequest__c
            WHERE Que_Status__c = 'In progress' AND CreatedById = :UserInfo.getUserId()
            WITH SECURITY_ENFORCED
            LIMIT 1
            FOR UPDATE
        ];
    }

    public List<Que_AsyncRequest__c> getAsyncRequestForUpdateById(Id asyncRequestId) {
        Logger.info(new LogMessage('getAsyncRequestForUpdateById({0})', asyncRequestId), asyncRequestId);

        return [
            SELECT
                Id
            FROM Que_AsyncRequest__c
            WHERE Que_Status__c = 'In progress' AND Id = :asyncRequestId
            WITH SECURITY_ENFORCED
            FOR UPDATE
        ];
    }
}