force-app/main/default/objects/Que_AsyncRequest__c/Que_AsyncRequest__c.object-meta.xml
<CustomObject>
    <description>Stores asynchronous requests</description>
    <label>Que_AsyncRequest</label>
    <nameField>
        <displayFormat>ar-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Que_AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Que_AsyncRequest__c/fields/Que_Params__c.field-meta.xml
<CustomField>
    <fullName>Que_Params__c</fullName>
    <description>Parameters for the current async operation</description>
    <label>Params</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/que/Que_ExecutorExample.cls
public with sharing class Que_ExecutorExample implements Que_IExecutable {
    public void execute(Que_AsyncRequest__c asyncRequest){
        Logger.info(new LogMessage('execute({0})', asyncRequest), asyncRequest.Id);

        if(asyncRequest.Que_Params__c == 'Exception'){
            String s;
            s.charat(5);
        }
    }

    public Boolean retryOnException(Que_AsyncRequest__c asyncRequest, Exception ex){
        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
        gen.writeStringField('exceptionType', ex.getTypeName());
        gen.writeStringField('message', ex.getMessage());
        gen.writeStringField('stackTrace', ex.getStackTraceString());
        gen.writeNumberField('lineNumber', ex.getLineNumber());
        gen.writeEndObject();
        String exceptionAsJSON = gen.getAsString();

        Logger.info(new LogMessage('attemptRetryOnException({0}, {1})', asyncRequest, exceptionAsJSON), asyncRequest.Id);
        return true;
    }
}